export const SERVICES = [
  {
    id: "ai-ml",
    name: "Automation",
    title: "AI & Machine Learning Automation",
    shortDesc: "Models and automations that take over the repetitive work: sorting, tagging, routing, reporting.",
    problem: "Your team re-types, re-sorts and re-checks the same data every day.",
    deliverables: ["Workflow automation", "ML model integration", "Custom bots and scripts"],
  },
  {
    id: "landing-page",
    name: "Landing pages",
    title: "Professional Landing Page Development",
    shortDesc: "Single pages built for one job: turning a campaign visit into an inquiry.",
    problem: "Ad traffic arrives and leaves because the page is slow or unclear.",
    deliverables: ["Conversion-led copy and layout", "Sub-second load times", "Form and tracking setup"],
  },
  {
    id: "company-profile",
    name: "Company profiles",
    title: "Company Profile Website",
    shortDesc: "A site that shows how your company really works and reads as credible in ten seconds.",
    problem: "Your website looks like every competitor's template.",
    deliverables: ["Brand-led design system", "CMS your team can edit", "Structure ready for more languages"],
  },
  {
    id: "ecommerce",
    name: "E-commerce",
    title: "E-commerce Development",
    shortDesc: "Storefronts, payments and inventory logic built for volume, not for a template.",
    problem: "Marketplace dependency and rigid, unscalable catalog structures.",
    deliverables: ["Custom storefronts", "Payment gateway integration", "Automated inventory logic"],
  },
  {
    id: "seo",
    name: "SEO",
    title: "SEO Optimization",
    shortDesc: "Technical and content groundwork that makes the right people find you.",
    problem: "Customers search for what you sell and find someone else.",
    deliverables: ["Technical SEO audit", "Content and URL structure", "Core Web Vitals fixes"],
  },
  {
    id: "analytics",
    name: "Analytics",
    title: "Digital Analytics & Data-Driven Solutions",
    shortDesc: "Event tracking and dashboards that show what visitors do and why they leave.",
    problem: "Decisions are made on instinct because the numbers are scattered or missing.",
    deliverables: ["Event tracking plan", "Custom dashboards", "Conversion rate optimization"],
  },
];
